### ISSUE TITLE
Is it possible to add BPC signal support?

### ISSUE THREAD

**Issue by Koukotsukan** [hzeller/txtempus#16]
Reference: 
https://en.wikipedia.org/wiki/BPC_(time_signal)
https://github.com/zenboss/BPC.js/blob/master/bpc.js

**Comment by hzeller** [comment]
It should be fairly straightforward in general, but looks like documentation is not really available.

If you want, you can try  starting from the JavaScript code you mentioned and extract what the format is from there.
Have a look at the interface to implement:
https://github.com/hzeller/txtempus/blob/master/time-signal-source.h

If you have such a watch or clock to receive the signal, you can verify if it works. The, please send a pull request with a new file `bpc-source.cc` and the necessary changes in main to wire it up.

**Comment by Koukotsukan** [comment]
Thank you
