### ISSUE TITLE
DCF77 weather protocol

### ISSUE THREAD

**Issue by VasylSamoilov** [hzeller/txtempus#28]
Can weather bits be added to DCF77 transmitter? 
Specification can be found here:
https://web.archive.org/web/20091229063350/http://www.hkw-elektronik.de/pdf/DB%20W-Protokoll-V%201.pdf

**Comment by JDat** [comment]
No, because it works differently. More info on mikrokontroller.de

**Comment by hzeller** [comment]
@VasylSamoilov Just from the documentation, it looks like you can add the bits if you have the weather information available from somewhere . You would add them then in the [DCF77 bit encoding](https://github.com/hzeller/txtempus/blob/master/src/dcf77-source.cc#L37-L50) - looks like they are encoded in the first 15 bits.

@JDat that is a somewhat generic URL (from a site that does not exist; typo ?) Do you have a direct link to a forum article that explains what you mean ?

**Comment by JDat** [comment]
Sorry, web link updated.
Data for weather information are encrypted. There was some unclear and mysterious hints on internet regarding encrypting/decrypting, but no actual code because it seriously break Meteotime company's copyrights.

**Comment by VasylSamoilov** [comment]
encoding and decoding algorithm is described here:
https://arduino-projects4u.com/meteotime/

**Comment by VasylSamoilov** [comment]
I have ported DCF77 weather encoder from osmocom-analog. Testing and feedback are welcome.

**Comment by seamusdemora** [comment]
What exactly is the point in encrypting the weather data?

**Comment by JDat** [comment]
> What exactly is the point in encrypting the weather data?

In short: business.

Swiss company Meteotime collaborated with DCF77 to use extra 13 (IRC) bits for they purpose and pay to DCF77 for that. But how to earn money if you need to pay for radio transmitter? Right, you write firmware and sell microcontroller to clock makers. Encrypt weather traffic and you are the only one who can use/license/sell it. Other will pay you for licensing/parts/MCU.

**Comment by seamusdemora** [comment]
Sounds like that is bordering on dishonesty...

**Comment by cmwik** [comment]
Could a maintainer or admin please review and remove the above comment from this thread? 

I believe the comment crosses the line from technical discussion into a disparaging remark about an entire nationality, which is both unprofessional and contrary to GitHub’s community standards. I’d like to keep this space focused on constructive, technical conversation, and I don’t want other contributors to feel unwelcome because of comments like this.

Thank you for taking a look.

**Comment by seamusdemora** [comment]
@cmwik 

> Could a maintainer or admin please review and remove the above comment from this thread?
> 
> I believe the comment crosses the line from technical discussion into a disparaging remark about an entire nationality, which is both unprofessional and contrary to GitHub’s community standards. I’d like to keep this space focused on constructive, technical conversation, and I don’t want other contributors to feel unwelcome because of comments like this.
> 
> Thank you for taking a look.

My apologies if you took this the wrong way...  BTW, are you of German nationality?
