### ISSUE TITLE
How do you increase the range?

### ISSUE THREAD

**Issue by melikyuksel** [hzeller/txtempus#4]
I'd like this to work throughout the house. How do I increase the range past the present "a few centimeters"?

**Comment by hzeller** [comment]
There are various ways, starting with antenna matching, but this is not advisable to stay within legal limits.
I don't want to give you any advise that brings you into trouble, so I encourage you to ask a local ham operator knowing your local legislation how to do this.

**Comment by icb-** [comment]
@hzeller do you have any field strength measurements with your recommended "antenna"? My reading of 47 CFR 18.305 (FCC regulation limiting unlicensed intentional radiators outside ISM bands) limits the maximum permissible field strength to 2400/F (in kHz) uV/m at 300m, or 40uV/m at 300m for 60kHz.

**Comment by hzeller** [comment]
I have not measured the coil, but I made the matching intentionally bad that it is good enough to reach my watch, but not much further.
Note that you'll get mostly inductive coupling with this kind of 'antenna'.

**Comment by melikyuksel** [comment]
Just enough for a room, perhaps? A few centimeters makes this useless for most things (wall clocks, in my case). And 77.5khz doesn’t interfere with anything here in the US anuwau.

**Comment by hzeller** [comment]
Should be doable. Ask your local ham op how.
