### ISSUE TITLE
Amplifier

### ISSUE THREAD

**Issue by Michael74ru** [hzeller/txtempus#5]
Hello!
How to make a signal amplifier? 3-5 meters for Meteostation RST 88777

**Comment by electrogoodie** [comment]
I tried making the antenna driver on his design and it works like a charm. Maybe this will help.

https://www.extremeelectronics.co.uk/msf-clock-be-wrong-rpi-msf-transmitter/

**Comment by HoracioDos** [comment]
> https://www.extremeelectronics.co.uk/msf-clock-be-wrong-rpi-msf-transmitter/

Cool article
Thanks!

**Comment by hzeller** [comment]
Andreas Spiess made a nice video that introduces you to building a more tuned circuit and also use a transistor to amplify https://www.youtube.com/watch?v=6SHGAEhnsYk
